/**
 * Drizzle schema (PostgreSQL) — Appendix A.7 of PLANO-TECNICO.md.
 * Models the Cinderak Burning campaign: gangs, fighters, equipment,
 * Sympathisers, challenges and Triumphs.
 */
import {
  pgTable,
  pgEnum,
  uuid,
  text,
  integer,
  boolean,
  timestamp,
  date,
  smallint,
  primaryKey,
  index,
  unique,
  check,
  vector,
} from "drizzle-orm/pg-core";
import { relations, sql } from "drizzle-orm";
import { GALLERY_CATEGORIES } from "@/lib/validation";

/** Embedding dimensions (OpenAI text-embedding-3-small). */
export const EMBEDDING_DIMENSIONS = 1536;

/* ----------------------------- Enums -------------------------------- */
export const campaignPhase = pgEnum("campaign_phase", [
  "great_darkness",
  "downtime",
  "spark_of_rebellion",
]);

export const userRole = pgEnum("user_role", ["admin", "player"]);

export const fighterCategory = pgEnum("fighter_category", [
  "leader",
  "champion",
  "prospect",
  "ganger",
  "juve",
  "crew",
  "hanger_on",
  "brute",
]);

export const fighterStatus = pgEnum("fighter_status", [
  "active",
  "in_recovery",
  "injured",
  "captured",
  "dead",
]);

export const equipmentCategory = pgEnum("equipment_category", [
  "weapon",
  "wargear",
  "skill",
  "armour",
  "upgrade",
]);

/** Campaign journal post kinds (issue #5). */
export const postType = pgEnum("post_type", [
  "session_report", // jogo que faz parte da campanha em andamento
  "chronicle", // história de personagens e acontecimentos
  "painting", // passo a passo / acompanhamento de pintura
  "news", // avisos e notícias gerais da campanha
  "battle_report", // jogo único, isolado (fora da campanha)
]);

/** Gallery albums (issues #6/#24) — mirrors GALLERY_CATEGORIES (validation.ts). */
export const galleryCategory = pgEnum("gallery_category", GALLERY_CATEGORIES);

/** Visitor comments are pre-moderated (issue #52): born pending, admin decides. */
export const galleryCommentStatus = pgEnum("gallery_comment_status", [
  "pending",
  "approved",
  "rejected",
]);

/* --------------------------- Tables -------------------------------- */
export const campaigns = pgTable("campaign", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  phase: campaignPhase("phase").notNull().default("great_darkness"),
  currentCycle: smallint("current_cycle").notNull().default(1),
  totalCycles: smallint("total_cycles").notNull().default(7),
  startDate: date("start_date"),
  endDate: date("end_date"),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const users = pgTable("app_user", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: text("email").notNull().unique(),
  role: userRole("role").notNull().default("player"),
  displayName: text("display_name").notNull(),
  isActive: boolean("is_active").notNull().default(true),
  // password hash generated by admin (no self-signup)
  passwordHash: text("password_hash"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const gangs = pgTable("gang", {
  id: uuid("id").defaultRandom().primaryKey(),
  campaignId: uuid("campaign_id")
    .notNull()
    .references(() => campaigns.id, { onDelete: "cascade" }),
  ownerUserId: uuid("owner_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  name: text("name").notNull(),
  house: text("house").notNull(),
  stashCredits: integer("stash_credits").notNull().default(0),
  reputation: integer("reputation").notNull().default(1),
  // derived values, recalculated on write (see lib/scoring.ts)
  ratingCached: integer("rating_cached").notNull().default(0),
  wealthCached: integer("wealth_cached").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const equipment = pgTable("equipment", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  category: equipmentCategory("category").notNull(),
  cost: integer("cost").notNull().default(0),
});

export const fighters = pgTable("fighter", {
  id: uuid("id").defaultRandom().primaryKey(),
  gangId: uuid("gang_id")
    .notNull()
    .references(() => gangs.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  category: fighterCategory("category").notNull(),
  baseCost: integer("base_cost").notNull().default(0),
  // characteristic profile (Fighter Card, p.78)
  m: smallint("m"),
  ws: smallint("ws"),
  bs: smallint("bs"),
  s: smallint("s"),
  t: smallint("t"),
  w: smallint("w"),
  i: smallint("i"),
  a: smallint("a"),
  ld: smallint("ld"),
  cl: smallint("cl"),
  wil: smallint("wil"),
  int: smallint("int"),
  xp: integer("xp").notNull().default(0),
  status: fighterStatus("status").notNull().default("active"),
  capturedByGangId: uuid("captured_by_gang_id"),
});

export const fighterEquipment = pgTable(
  "fighter_equipment",
  {
    fighterId: uuid("fighter_id")
      .notNull()
      .references(() => fighters.id, { onDelete: "cascade" }),
    equipmentId: uuid("equipment_id")
      .notNull()
      .references(() => equipment.id, { onDelete: "cascade" }),
    qty: integer("qty").notNull().default(1),
  },
  (t) => [primaryKey({ columns: [t.fighterId, t.equipmentId] })],
);

export const stashItems = pgTable("stash_item", {
  id: uuid("id").defaultRandom().primaryKey(),
  gangId: uuid("gang_id")
    .notNull()
    .references(() => gangs.id, { onDelete: "cascade" }),
  equipmentId: uuid("equipment_id")
    .notNull()
    .references(() => equipment.id, { onDelete: "cascade" }),
  qty: integer("qty").notNull().default(1),
});

export const sympathisers = pgTable("sympathiser", {
  id: text("id").primaryKey(), // stable slug (e.g. "fallen-house")
  name: text("name").notNull(),
  // the Arbitrator chooses which Sympathisers are active in the campaign
  enabled: boolean("enabled").notNull().default(true),
});

export const sympathiserControl = pgTable("sympathiser_control", {
  id: uuid("id").defaultRandom().primaryKey(),
  sympathiserId: text("sympathiser_id")
    .notNull()
    .references(() => sympathisers.id, { onDelete: "cascade" }),
  gangId: uuid("gang_id").references(() => gangs.id, { onDelete: "cascade" }),
  sinceCycle: smallint("since_cycle").notNull().default(1),
  isCurrent: boolean("is_current").notNull().default(true),
});

export const challenges = pgTable("challenge", {
  id: uuid("id").defaultRandom().primaryKey(),
  campaignId: uuid("campaign_id")
    .notNull()
    .references(() => campaigns.id, { onDelete: "cascade" }),
  cycle: smallint("cycle").notNull(),
  challengerGangId: uuid("challenger_gang_id")
    .notNull()
    .references(() => gangs.id, { onDelete: "cascade" }),
  challengedGangId: uuid("challenged_gang_id").references(() => gangs.id, {
    onDelete: "cascade",
  }),
  sympathiserId: text("sympathiser_id").references(() => sympathisers.id),
  scenario: text("scenario"),
  outcome: text("outcome"), // "challenger_win" | "challenged_win" | "declined" | "draw"
  resolved: boolean("resolved").notNull().default(false),
  playedAt: timestamp("played_at"),
});

export const triumphs = pgTable("triumph", {
  id: uuid("id").defaultRandom().primaryKey(),
  campaignId: uuid("campaign_id")
    .notNull()
    .references(() => campaigns.id, { onDelete: "cascade" }),
  gangId: uuid("gang_id").references(() => gangs.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  awardedAt: timestamp("awarded_at").notNull().defaultNow(),
});

/**
 * Campaign journal posts (issue #5). Bilingual like the content pages
 * (issue #12): English is the default, PT-BR is the display translation;
 * logic keys (slug, type) stay in English. Bodies are Markdown, rendered
 * with react-markdown (raw HTML disabled).
 */
export const posts = pgTable(
  "post",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    slug: text("slug").notNull().unique(),
    type: postType("type").notNull().default("news"),
    titleEn: text("title_en").notNull(),
    titlePt: text("title_pt").notNull(),
    excerptEn: text("excerpt_en").notNull().default(""),
    excerptPt: text("excerpt_pt").notNull().default(""),
    bodyEn: text("body_en").notNull(),
    bodyPt: text("body_pt").notNull(),
    /** Absolute URL (Supabase Storage) or site-relative path (/reports/…). */
    coverImage: text("cover_image"),
    coverAlt: text("cover_alt"),
    published: boolean("published").notNull().default(false),
    publishedAt: timestamp("published_at"),
    authorUserId: uuid("author_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [index("post_published_at_idx").on(t.published, t.publishedAt)],
);

/**
 * Gallery images (issues #6/#24) — metadata for objects in the public
 * `gallery` bucket on Supabase Storage. The object itself lives at
 * `gallery/<path>` (path is prefixed by category, e.g. "battle/…"); the row
 * carries everything the site needs to render the grid without touching
 * storage: dimensions (next/image layout), alt/captions (en/pt) and filters.
 */
export const galleryImages = pgTable(
  "gallery_image",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    /** Object path inside the gallery bucket ("battle/foo-a1b2c3.webp"). */
    path: text("path").notNull().unique(),
    category: galleryCategory("category").notNull().default("misc"),
    /** Free-form lowercase tags (gang names, scenario, etc.). */
    tags: text("tags").array().notNull().default([]),
    altEn: text("alt_en").notNull(),
    altPt: text("alt_pt").notNull().default(""),
    captionEn: text("caption_en").notNull().default(""),
    captionPt: text("caption_pt").notNull().default(""),
    /** Intrinsic pixel size — required by next/image to avoid layout shift. */
    width: integer("width").notNull(),
    height: integer("height").notNull(),
    mime: text("mime").notNull(),
    bytes: integer("bytes").notNull(),
    /**
     * Who painted the miniatures on the photo (issue #52) — display-only text,
     * distinct from uploadedByUserId (who uploaded ≠ who painted). Rendered
     * highlighted ("PAINTED BY // NAME") on the card caption and lightbox.
     */
    authorName: text("author_name").notNull().default(""),
    published: boolean("published").notNull().default(true),
    uploadedByUserId: uuid("uploaded_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("gallery_image_pub_idx").on(t.published, t.createdAt),
    index("gallery_image_category_idx").on(t.category),
  ],
);

/**
 * Anonymous 1–5 star ratings on gallery photos (issue #52).
 * The voter is identified only by `voter_hash` = HMAC-SHA256 of a random
 * UUID stored in an httpOnly cookie (see src/lib/gallery-visitor.ts) — no IP
 * or raw identifier is ever persisted (LGPD). One vote per visitor per image
 * (unique constraint); voting again upserts the new value.
 */
export const galleryRatings = pgTable(
  "gallery_rating",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    imageId: uuid("image_id")
      .notNull()
      .references(() => galleryImages.id, { onDelete: "cascade" }),
    rating: smallint("rating").notNull(),
    voterHash: text("voter_hash").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    unique("gallery_rating_image_voter_uq").on(t.imageId, t.voterHash),
    check("gallery_rating_range_ck", sql`${t.rating} between 1 and 5`),
  ],
);

/**
 * Anonymous, pre-moderated comments on gallery photos (issue #52).
 * Born `pending`; only `approved` rows are ever served to the public API.
 * `voter_hash` mirrors gallery_rating (abuse tracing, never displayed).
 */
export const galleryComments = pgTable(
  "gallery_comment",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    imageId: uuid("image_id")
      .notNull()
      .references(() => galleryImages.id, { onDelete: "cascade" }),
    authorName: text("author_name").notNull(),
    body: text("body").notNull(),
    status: galleryCommentStatus("status").notNull().default("pending"),
    voterHash: text("voter_hash").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("gallery_comment_image_idx").on(t.imageId, t.status, t.createdAt),
  ],
);

/**
 * Vectorised rule chunks for the AI assistant (RAG).
 * Requires the pgvector extension: CREATE EXTENSION IF NOT EXISTS vector;
 */
export const ruleChunks = pgTable(
  "rule_chunk",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    source: text("source").notNull(), // file/origin of the chunk
    book: text("book"), // official book title (when applicable)
    page: integer("page"), // book page number (for manual verification)
    heading: text("heading").notNull().default(""),
    content: text("content").notNull(),
    embedding: vector("embedding", {
      dimensions: EMBEDDING_DIMENSIONS,
    }).notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [
    index("rule_chunk_embedding_idx").using(
      "hnsw",
      t.embedding.op("vector_cosine_ops"),
    ),
  ],
);

/* --------------------------- Relations ------------------------------ */
export const gangsRelations = relations(gangs, ({ many, one }) => ({
  fighters: many(fighters),
  stash: many(stashItems),
  owner: one(users, {
    fields: [gangs.ownerUserId],
    references: [users.id],
  }),
  campaign: one(campaigns, {
    fields: [gangs.campaignId],
    references: [campaigns.id],
  }),
}));

export const fightersRelations = relations(fighters, ({ many, one }) => ({
  gang: one(gangs, { fields: [fighters.gangId], references: [gangs.id] }),
  equipment: many(fighterEquipment),
}));

export const fighterEquipmentRelations = relations(
  fighterEquipment,
  ({ one }) => ({
    fighter: one(fighters, {
      fields: [fighterEquipment.fighterId],
      references: [fighters.id],
    }),
    equipment: one(equipment, {
      fields: [fighterEquipment.equipmentId],
      references: [equipment.id],
    }),
  }),
);

export const stashItemsRelations = relations(stashItems, ({ one }) => ({
  gang: one(gangs, { fields: [stashItems.gangId], references: [gangs.id] }),
  equipment: one(equipment, {
    fields: [stashItems.equipmentId],
    references: [equipment.id],
  }),
}));

export const usersRelations = relations(users, ({ many }) => ({
  gangs: many(gangs),
  posts: many(posts),
}));

export const postsRelations = relations(posts, ({ one }) => ({
  author: one(users, {
    fields: [posts.authorUserId],
    references: [users.id],
  }),
}));

export const campaignsRelations = relations(campaigns, ({ many }) => ({
  gangs: many(gangs),
}));

export const galleryImagesRelations = relations(galleryImages, ({ many }) => ({
  ratings: many(galleryRatings),
  comments: many(galleryComments),
}));

export const galleryRatingsRelations = relations(galleryRatings, ({ one }) => ({
  image: one(galleryImages, {
    fields: [galleryRatings.imageId],
    references: [galleryImages.id],
  }),
}));

export const galleryCommentsRelations = relations(galleryComments, ({ one }) => ({
  image: one(galleryImages, {
    fields: [galleryComments.imageId],
    references: [galleryImages.id],
  }),
}));
