-- ---------------------------------------------------------------------------
-- Supabase structure for the photo gallery + media storage (issues #6/#24).
--
-- Idempotent: safe to run more than once (SQL editor of the Supabase
-- dashboard, or psql against DATABASE_URL). Mirrors src/lib/db/schema.ts —
-- keep both in sync (this project uses drizzle-kit push, no migration files).
--
-- Storage access model (no RLS policies needed):
--   * buckets are PUBLIC → reads go through /storage/v1/object/public/…
--   * writes only happen server-side with the service role key, or through
--     signed upload URLs generated by it (see src/lib/storage.ts).
-- ---------------------------------------------------------------------------

-- 1) Enum dos álbuns -------------------------------------------------------
do $$ begin
  create type public.gallery_category as enum
    ('battle', 'painting', 'gang', 'terrain', 'misc');
exception
  when duplicate_object then null;
end $$;

-- 2) Tabela de metadados ---------------------------------------------------
create table if not exists public.gallery_image (
  id                  uuid primary key default gen_random_uuid(),
  path                text not null unique,
  category            public.gallery_category not null default 'misc',
  tags                text[] not null default '{}',
  alt_en              text not null,
  alt_pt              text not null default '',
  caption_en          text not null default '',
  caption_pt          text not null default '',
  width               integer not null,
  height              integer not null,
  mime                text not null,
  bytes               integer not null,
  published           boolean not null default true,
  uploaded_by_user_id uuid references public.app_user(id) on delete set null,
  created_at          timestamp not null default now()
);

create index if not exists gallery_image_pub_idx
  on public.gallery_image (published, created_at);
create index if not exists gallery_image_category_idx
  on public.gallery_image (category);

-- 3) Buckets ---------------------------------------------------------------
-- gallery: fotos da campanha (10 MB por arquivo, só imagens)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'gallery', 'gallery', true, 10485760,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public             = excluded.public,
  file_size_limit    = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- media: arquivos estáticos grandes (trailer etc. — 50 MB, só vídeo mp4/webm)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media', 'media', true, 52428800,
  array['video/mp4', 'video/webm']
)
on conflict (id) do update set
  public             = excluded.public,
  file_size_limit    = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- 4) Conferência -----------------------------------------------------------
select 'gallery_image ready' as status, count(*) as rows_now from public.gallery_image;
select id, public, file_size_limit, allowed_mime_types
  from storage.buckets where id in ('gallery', 'media', 'reports');
